### ISSUE TITLE
Support plain-text notes

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#14]
I find text/plain notes quick to edit, no need to click around just to add a bit of formatting. However the app apparently tries to interpret the body. For example, I often paste from the Internet within angle brackets (`<<text>>`) which are common quote characters in Italian; the app then displays `<>`.

**Comment by niendo1** [comment]
On my android it is working...correctly.
At the moment I don't touch the clipboard at all. maybe there is a way to add a option paste as Text or something.
I have the option paste as text (without format), when I insert text.

And its also possible to support only plain/text at all (or mark down)...but it will take some time

**Comment by opk12** [comment]
I mean that this email message shows as `<>` instead of `<<hello>>`

```yaml
Date: Wed, 15 Feb 2023 09:58:31 +0100
Subject: 
MIME-Version: 1.0
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable
From: Test

<<hello>>
```
